# Generated by Django 3.2 on 2021-04-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('user_created', models.DateTimeField(auto_now_add=True, help_text='유저 생성 시점')),
                ('last_login', models.DateTimeField(auto_now=True, help_text='유저의 마지막 로그인 logging')),
                ('withdrew_at', models.DateTimeField(blank=True, null=True, verbose_name='탈퇴 시점')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=31)),
                ('birth_day', models.CharField(blank=True, help_text='생년월일', max_length=32)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('mygit', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(default='red.jpg', upload_to='profile/image')),
                ('myInfo', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
